In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("events.csv")
print(df.shape)

(513368, 9)

In [4]:
print(df.columns)

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

In [6]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2020-09-24 11:57:06 UTC,view,1996170,2144415922528452715,electronics.telephone,NaN,31.90,1.515916e+18,LJuJVLEjPT
1,2020-09-24 11:57:26 UTC,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1.515916e+18,tdicluNnRY
2,2020-09-24 11:57:27 UTC,view,215454,2144415927158964449,NaN,NaN,9.81,1.515916e+18,4TMArHtXQy
3,2020-09-24 11:57:33 UTC,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1.515916e+18,aGFYrNgC08
4,2020-09-24 11:57:36 UTC,view,3658723,2144415921169498184,NaN,cameronsino,15.87,1.515916e+18,aa4mmk0kwQ

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 513368 entries, 0 to 513367
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   event_time     513368 non-null  object
 1   event_type     513368 non-null  object
 2   product_id     513368 non-null  int64
 3   category_id    513368 non-null  int64
 4   category_code  366280 non-null  object
 5   brand          386053 non-null  object
 6   price          513367 non-null  float64
 7   user_id        513367 non-null  float64
 8   user_session   513228 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 35.3+ MB

In [8]:
df.isnull().sum()

event_time            0
event_type            0
product_id            0
category_id           0
category_code    147088
brand            127315
price                 1
user_id               1
user_session        140
dtype: int64

In [9]:
print(
    df["event_type"]
    .value_counts()
)

event_type
view        463957
cart         28796
purchase     20615
Name: count, dtype: int64

In [10]:
df["event_time"] = pd.to_datetime(
    df["event_time"]
)

In [11]:
print(
    df["event_time"].min()
)

print(
    df["event_time"].max()
)

2020-09-24 11:57:06+00:00
2020-12-28 02:21:05+00:00